spring:
  application:
    name: taxi-client
  profiles:
    active: dev
      #,http://localhost:7900/eureka,http://localhost:7900/eureka

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 # Nacos服务器地址
      config:
        server-addr: 127.0.0.1:8848 # Nacos服务器地址
        file-extension: yaml