server:
  port: 7902

spring:
  cloud:
    nacos:
      discovery:
        server-addr: http://localhost:8848/nacos # Nacos服务器地址
      config:
        server-addr: http://localhost:8848/nacos # Nacos服务器地址
        file-extension: yaml